apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/osdp-wildcard-gw
  hosts:
    - {{ .Values.appName }}.{{ .Values.domain }}
  http:
    - route:
        - destination:
            host: {{ .Values.appName }}
            port:
              number: {{ .Values.service.port }}
